# permissions for end users to view trinoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: trino-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hive-metadata-operator
    app.kubernetes.io/part-of: hive-metadata-operator
    app.kubernetes.io/managed-by: kustomize
  name: trino-viewer-role
rules:
- apiGroups:
  - stack.zncdata.net
  resources:
  - trinoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - stack.zncdata.net
  resources:
  - trinoes/status
  verbs:
  - get
