apiVersion: stack.zncdata.net/v1alpha1
kind: Trino
metadata:
  labels:
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino-sample
    app.kubernetes.io/part-of: hive-metadata-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: hive-metadata-operator
  name: trino-sample
spec:
  # TODO(user): Add fields here
